### ISSUE TITLE
Favorites settings disappearing

### ISSUE THREAD

**Issue by Temreki** [FluffierThanThou/WorkTab#111]
When I set up favorites for work priorities and assign them to my colonists, then save my game and exit, some of the work priorities are blank when I load the save. It seems to happen to random colonists/favorites and affects random jobs. This is not an issue outside of the use of favorites.

In my save game, all colonists and all favorites have all jobs set to 1. Upon loading, about 10% of the jobs are blank.

I have many other mods on my main save right now, but this is happening with brand new games with 0 additional mods.

Am I doing something wrong?

Log
https://drive.google.com/open?id=1n4DzqN_9NJhABaYZTK4QfZ-16vwpppri
Save
https://drive.google.com/open?id=1oA8KFGv1j1UMMcHu_6n0JfdMdONCM3uE

**Comment by FluffierThanThou** [comment]
Thanks for the report. Unfortunately, I'm not able to replicate your issue. There appears to be nothing wrong with the save file, and the output_log contains a bunch of unrelated errors that basically invalidate anything I might find.

If you keep encountering this issue, more (and cleaner) output logs would be appreciated.
