### ISSUE TITLE
Possible to make Work Tab compatible with mod "Multiplayer"?

### ISSUE THREAD

**Issue by Contik** [FluffierThanThou/WorkTab#112]
Currently Work Tab is listed as "Does not work" in [Multiplayer](https://github.com/Zetrith/Multiplayer)'s [mod support list](https://github.com/Zetrith/Multiplayer/wiki/Mod-support). Is it feasible making Work Tab compatible with multiplayer?

*//edit: the mod support list specifically mentions multiplayer desyncs and that mods adding GUI elements, thereby causing desyncs aren't supported. I'm not entirely sure if that fits all GUI additions always or if maybe Work Tab is somehow exempt from that phenomenon :)*

**Comment by nodice-gaming** [comment]
Must admit I find Rimworld almost unplayable without Work Tab after having used it for so long. I too would love to see this if it is possible!

**Comment by YellowOnion** [comment]
Why was this closed? Was it added? I noticed some commented out multiplayer detection code in a few files.

Edit: had a further look around, doesn't look like it's been patched, tried building the project in VS, but some issues with failing to execute "mod update"...

**Comment by ghost** [comment]
Can we please reopen this? I want it in multiplayer please... its necessary.
