### ISSUE TITLE
Favourite stored priorities get updated with pawn priority changes

### ISSUE THREAD

**Issue by Grogfeld** [FluffierThanThou/WorkTab#12]
Assigned template copy job priorities from Pawn that was originally created from and not from actually template. 
How to reproduce:
1. Create template
2. Change priority on one job (therefore Template icon will reset)
3. Assign this template to other pawn and job that was change in point 2. will be assign for new pawn, and not as should from the point 1.

Maybe not a bug but an issue that somehow bothers me.

**Comment by FluffierThanThou** [comment]
From steam release; 
Steps to reproduce:
Clear all priorities
Set one Char A skill to 1
Save as favorite
Change same Char A skill to 2
Apply the favorite to Char B
Char B's skill value will be 2, not 1. Expect it to be 1.
