### ISSUE TITLE
Crash when clicking colonists before they land with CCL and CCL+Vanilla tweaks loaded.

### ISSUE THREAD

**Issue by FeedingWolves** [FluffierThanThou/WorkTab#13]
Title, basically. double clicking a colonist before they land during the pause phase with the mods loaded causes a crash. Tested with only those mods active, consistent with every test.

Load order is as follows.

Core
CCL
CCL+Vanilla Tweaks
Work Tabs

**Comment by Drogean** [comment]
glad i'm not the only one - can confirm work tabs is the source to this issue

**Comment by FluffierThanThou** [comment]
note to self; probably related to position not being set.

**Comment by FluffierThanThou** [comment]
unable to replicate with A16 / HugsLib.
