### ISSUE TITLE
ModConfigMenu errors when opened from main menu

### ISSUE THREAD

**Issue by kaptain-kavern** [FluffierThanThou/WorkTab#17]
![error message](https://i.imgur.com/4GIY4xR.jpg)

with only CCL + Fluffy Tab

![modlist](https://i.imgur.com/7awbysP.jpg)

And I put you the [output_log.txt](https://github.com/FluffierThanThou/Fluffy_Tabs/files/411627/output_log.txt), here.

Haven't yet tried to launch a game with it though

**Comment by FluffierThanThou** [comment]
Yeah, I'm aware of this one. The problem is that the settings available for change in the MCM reside in the mod's MapComponent, but the MapComponent is ofcourse only loaded on starting a game. 

It works fine in game for now. I'll fix this in the (near) future.

**Comment by biship** [comment]
Ah, I get this too. Was just about to report it :)

**Comment by kaptain-kavern** [comment]
I confirm that aside from the error msg i reported, all things works fine (after several hours of actual gaming at last ^^)

**Comment by DeepRogger** [comment]
Hi,your mod is amazing! I likes too much. Sorry for my english not well. Just hope this complete one with less bugs can come soon. 
I was so depressed with the bug for days. cause i really love it(the work tab mod was no.1 and all the others you made ) 
Thx for your great mods.

**Comment by FluffierThanThou** [comment]
obsolete with move to hugslib
