### ISSUE TITLE
Implement row functionality similar to current column functionality.

### ISSUE THREAD

**Issue by FluffierThanThou** [FluffierThanThou/WorkTab#18]
Tikigod 1 hour ago  
Like 123Nick suggested having the column behaviour applied to rows as well could be handy, especially for DT mode. 

So if you wanted to give an individual colonist a new task as their main priority and just shift the existing assignment scales by 1 point you could use shift-click on the row to change all existing priorities for that single colonist by 1 and then assign the new job you want to be their main focus.

Would save so much damn time than manually shifting everything for that colonist by 1.

**Comment by frenchiveruti** [comment]
Yes please! If I want to make my guy to do something at x hour I have to go one by one and then place the thing I want to 1, and it takes so damn long!
