### ISSUE TITLE
Re-implement workgiver/worktype reordering?

### ISSUE THREAD

**Issue by Mythos** [FluffierThanThou/WorkTab#19]
Hello,

I want to play without numeric priorities as they are too much for me. With the checkboxes it works, but I want the "Managing" task to be a higher priority and not the least one.
I don't remember which one, but there was a mod which allowed reorderung the columns.

Regards,
Mythos

**Comment by FluffierThanThou** [comment]
Hey Mythos, 

What you're talking about is my old work tab, I took the functionality out of the new one because it's effectively replaced by the detailed priorities view. That said, I can see some use for it still, I may add it back in.

**Comment by Mythos** [comment]
Thanks for your answer, I already thought it was your mod. ;)
Nice to hear that it could come back.
Speaking of detailed priorities: Some stuff is being cut off, managing is not visible at all.
