### ISSUE TITLE
Colonist with certain skills disabled (and not configurable) starts using these skills after installing work tab

### ISSUE THREAD

**Issue by jjwa** [FluffierThanThou/WorkTab#23]
Colonist 'Big T' is incapable of skilled labour. Cooking, construction, growing, mining and crafting are disabled. Which also means I can't give them a priority. But he has now started cooking and building. Still can't configure the priority for these jobs.

http://imgur.com/a/u9OKN Screenshots of him building, cooking, his character screen, the normal and big work tab, mod options and mod loading order.

Savegame attached.
[PlanetonBigTisweird.zip](https://github.com/FluffierThanThou/Fluffy_Tabs/files/428849/PlanetonBigTisweird.zip)

Request: follow the game's 'incapabilities' :)

**Comment by FluffierThanThou** [comment]
fixed, will be included in next release
