### ISSUE TITLE
A16 UI scaling breaks the WorkTab UI

### ISSUE THREAD

**Issue by Kiyiko** [FluffierThanThou/WorkTab#25]
![0dfsav9](https://cloud.githubusercontent.com/assets/4523694/21509558/c6a94ad2-cc4f-11e6-8ac7-ead8aa317703.jpg)

**Comment by FluffierThanThou** [comment]
I've made some progress in fixing this one in v0.16.1.8, but something in the rotation is still eluding me - the labels are still in the wrong place.

I may end up taking a completely different approach altogether, as the current approach has a clipping issue on the far-right labels as well.

**Comment by FluffierThanThou** [comment]
Going in a different direction for A17
