### ISSUE TITLE
[Issue] "saved" work priorities won't remember time-schedules

### ISSUE THREAD

**Issue by frenchiveruti** [FluffierThanThou/WorkTab#34]
So, I had to modify the priorities of the colony and that broke the "time scheduled" work priorities, the thing is that I previously saved all my colonists in individual "favorite" configurations (by the way check #33), and now when I restored them I don't have the "scheduled" ones such as "from 8am to 13am x building priority is 1".

**Comment by FluffierThanThou** [comment]
I can't replicate this bug, but I did find that assigning a favourite doesn't correctly set the 'time dependent' flag for the checkboxes, meaning that the little icon and tooltip wouldn't show up until you changed another priority. 

Could you verify if this was indeed what was happening for you, or if there's something else I need to fix?

**Comment by frenchiveruti** [comment]
Ok I'll try to snatch a video or something so it's easier to understand the issue. 
I don't know when I'll be able to drop it here but Soon™

**Comment by frenchiveruti** [comment]
Here you go, I tried to make it the best I could
https://www.youtube.com/watch?v=Yfi7R3Kec9Q&feature=youtu.be

**Comment by frenchiveruti** [comment]
Hey @FluffierThanThou , I don't know if you get the notification, were you able to watch the video?

**Comment by FluffierThanThou** [comment]
hey french, 

I did, but hadn't had time yet. I've just watched it, but it looks like it could be the bug I fixed. The problem was that while the priorities were applied, the little icon and tooltip were not updated when applying a favourite. So the only way to see it applied would be to look at one of the hours it was scheduled.

I'll double check again to see if I can replicate this, since I assume this behaviour is still happening for you even after the latest update(s)?

**Comment by FluffierThanThou** [comment]
I still can't replicate this on my machine. Please provide an output_log, it might contain some more information. You can normally find the output log in the following location;
`C:\Program Files\Steam\steamapps\common\RimWorld\RimWorldWin_Data\output_log.txt`

If you changed the steam install location, alter the path accordingly.

**Comment by frenchiveruti** [comment]
Hey there, I downloaded the last version but didn't try to use the function again, now it works as expected, thanks a lot!
