### ISSUE TITLE
WorkTab produces weird tooltip with schedules in simple mode

### ISSUE THREAD

**Issue by Pichu0102** [FluffierThanThou/WorkTab#35]
![294100_20170109000631_1](https://cloud.githubusercontent.com/assets/4944941/21757653/f638061c-d5ff-11e6-870f-15f2d5ad383f.png)

It does display the set times in the expanded all work kinds advanced mode, but not in simple mode.

**Comment by FluffierThanThou** [comment]
looks like a missing translation key, I'll look into it
