### ISSUE TITLE
Ignoring disallowed work types

### ISSUE THREAD

**Issue by Chaza218** [FluffierThanThou/WorkTab#38]
Hi,

I have noticed that some workers will ignore their disallowed work types when using this mod. AN example would be a worker who is incapable of intellectual doing research despite not even having a tick box for that job

**Comment by DingoDjango** [comment]
I recall seeing this in A14 as well.

**Comment by FluffierThanThou** [comment]
Thanks for reporting! Please provide an output_log so I can figure out what exactly is going on. You can normally find the output log in the following location;
`C:\Program Files\Steam\steamapps\common\RimWorld\RimWorldWin_Data\output_log.txt`

If you changed the steam install location, alter the path accordingly.

**Comment by Chaza218** [comment]
Initialize engine version: 5.4.1f1 (649f48bbbf0f)
GfxDevice: creating device client; threaded=1
Direct3D:
    Version:  Direct3D 9.0c [igdumd32.dll 9.17.10.4229]
    Renderer: Intel(R) HD Graphics 3000
    Vendor:   Intel
    VRAM:     848 MB (via DXGI)
    Caps:     Shader=30 DepthRT=1 NativeDepth=1 NativeShadow=1 DF16=1 INTZ=1 NULL=1 RESZ=1 SlowINTZ=0 ATOC=1
Begin MonoManager ReloadAssembly
Platform assembly: C:\Program Files (x86)\Steam\steamapps\common\RimWorld\RimWorldWin_Data\Managed\UnityEngine.dll (this message is harmless)
Loading C:\Program Files (x86)\Steam\steamapps\common\RimWorld\RimWorldWin_Data\Managed\UnityEngine.dll into Unity Child Domain
Platform assembly: C:\Program Files (x86)\Steam\steamapps\common\RimWorld\RimWorldWin_Data\Managed\Assembly-CSharp-firstpass.dll (this message is harmless)
Loading C:\Program Files (x86)\Steam\steamapps\common\RimWorld\RimWorldWin_Data\Managed\Assembly-CSharp-firstpass.dll into Unity Child Domain
Platform assembly: C:\Program Files (x86)\Steam\steamapps\common\RimWorld\RimWorldWin_Data\Managed\Assembly-CSharp.dll (this message is harmless)
Loading C:\Program Files (x86)\Steam\steamapps\common\RimWorld\RimWorldWin_Data\Managed\Assembly-CSharp.dll into Unity Child Domain
Platform assembly: C:\Program Files (x86)\Steam\steamapps\common\RimWorld\RimWorldWin_Data\Managed\UnityEngine.UI.dll (this message is harmless)
Loading C:\Program Files (x86)\Steam\steamapps\common\RimWorld\RimWorldWin_Data\Managed\UnityEngine.UI.dll into Unity Child Domain
Platform assembly: C:\Program Files (x86)\Steam\steamapps\common\RimWorld\RimWorldWin_Data\Managed\UnityEngine.Networking.dll (this message is harmless)
Loading C:\Program Files (x86)\Steam\steamapps\common\RimWorld\RimWorldWin_Data\Managed\UnityEngine.Networking.dll into Unity Child Domain
Platform assembly: C:\Program Files (x86)\Steam\steamapps\common\RimWorld\RimWorldWin_Data\Managed\System.Xml.Linq.dll (this message is harmless)
Loading C:\Program Files (x86)\Steam\steamapps\common\RimWorld\RimWorldWin_Data\Managed\System.Xml.Linq.dll into Unity Child Domain
Platform assembly: C:\Program Files (x86)\Steam\steamapps\common\RimWorld\RimWorldWin_Data\Managed\NAudio.dll (this message is harmless)
Loading C:\Program Files (x86)\Steam\steamapps\common\RimWorld\RimWorldWin_Data\Managed\NAudio.dll into Unity Child Domain
Platform assembly: C:\Program Files (x86)\Steam\steamapps\common\RimWorld\RimWorldWin_Data\Managed\NVorbis.dll (this message is harmless)
Loading C:\Program Files (x86)\Steam\steamapps\common\RimWorld\RimWorldWin_Data\Managed\NVorbis.dll into Unity Child Domain
- Completed reload, in  0.684 seconds
Platform assembly: C:\Program Files (x86)\Steam\steamapps\common\RimWorld\RimWorldWin_Data\Managed\System.Core.dll (this message is harmless)
Platform assembly: C:\Program Files (x86)\Steam\steamapps\common\RimWorld\RimWorldWin_Data\Managed\System.dll (this message is harmless)
Platform assembly: C:\Program Files (x86)\Steam\steamapps\common\RimWorld\RimWorldWin_Data\Managed\System.Xml.dll (this message is harmless)
<RI> Initializing input.

<RI> Input initialized.

desktop: 1600x900 60Hz; virtual: 1600x900 at 0,0
<RI> Initialized touch support.

UnloadTime: 1.103344 ms
RimWorld 0.16.1393 rev536
 
(Filename: C:/buildslave/unity/build/artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 42)

Non platform assembly: data-16120048 (this message is harmless)
Fallback handler could not load library C:/Program Files (x86)/Steam/steamapps/common/RimWorld/RimWorldWin_Data/Mono/data-16120048.dll
Non platform assembly: data-0F74F010 (this message is harmless)
Fallback handler could not load library C:/Program Files (x86)/Steam/steamapps/common/RimWorld/RimWorldWin_Data/Mono/data-0F74F010.dll
Non platform assembly: data-1613CDE8 (this message is harmless)
Fallback handler could not load library C:/Program Files (x86)/Steam/steamapps/common/RimWorld/RimWorldWin_Data/Mono/data-1613CDE8.dll
Non platform assembly: data-0F75BE18 (this message is harmless)
Fallback handler could not load library C:/Program Files (x86)/Steam/steamapps/common/RimWorld/RimWorldWin_Data/Mono/data-0F75BE18.dll
Platform assembly: C:\Program Files (x86)\Steam\steamapps\common\RimWorld\RimWorldWin_Data\Managed\System.Configuration.dll (this message is harmless)
Non platform assembly: data-161D9008 (this message is harmless)
Fallback handler could not load library C:/Program Files (x86)/Steam/steamapps/common/RimWorld/RimWorldWin_Data/Mono/data-161D9008.dll
Non platform assembly: data-0F620058 (this message is harmless)
Fallback handler could not load library C:/Program Files (x86)/Steam/steamapps/common/RimWorld/RimWorldWin_Data/Mono/data-0F620058.dll
Non platform assembly: data-161DFD60 (this message is harmless)
Fallback handler could not load library C:/Program Files (x86)/Steam/steamapps/common/RimWorld/RimWorldWin_Data/Mono/data-161DFD60.dll
Non platform assembly: data-161EFCD8 (this message is harmless)
Fallback handler could not load library C:/Program Files (x86)/Steam/steamapps/common/RimWorld/RimWorldWin_Data/Mono/data-161EFCD8.dll
We're all good!
 
(Filename: C:/buildslave/unity/build/artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 42)

Non platform assembly: data-1620F008 (this message is harmless)
Fallback handler could not load library C:/Program Files (x86)/Steam/steamapps/common/RimWorld/RimWorldWin_Data/Mono/data-1620F008.dll
Non platform assembly: data-1621EA50 (this message is harmless)
Fallback handler could not load library C:/Program Files (x86)/Steam/steamapps/common/RimWorld/RimWorldWin_Data/Mono/data-1621EA50.dll
Non platform assembly: data-16223A58 (this message is harmless)
Fallback handler could not load library C:/Program Files (x86)/Steam/steamapps/common/RimWorld/RimWorldWin_Data/Mono/data-16223A58.dll
Non platform assembly: data-16233008 (this message is harmless)
Fallback handler could not load library C:/Program Files (x86)/Steam/steamapps/common/RimWorld/RimWorldWin_Data/Mono/data-16233008.dll
Non platform assembly: data-1623F618 (this message is harmless)
Fallback handler could not load library C:/Program Files (x86)/Steam/steamapps/common/RimWorld/RimWorldWin_Data/Mono/data-1623F618.dll
Non platform assembly: data-16240E20 (this message is harmless)
Fallback handler could not load library C:/Program Files (x86)/Steam/steamapps/common/RimWorld/RimWorldWin_Data/Mono/data-16240E20.dll
Non platform assembly: data-16242428 (this message is harmless)
Fallback handler could not load library C:/Program Files (x86)/Steam/steamapps/common/RimWorld/RimWorldWin_Data/Mono/data-16242428.dll
Non platform assembly: data-16244638 (this message is harmless)
Fallback handler could not load library C:/Program Files (x86)/Steam/steamapps/common/RimWorld/RimWorldWin_Data/Mono/data-16244638.dll
Non platform assembly: data-16247A40 (this message is harmless)
Fallback handler could not load library C:/Program Files (x86)/Steam/steamapps/common/RimWorld/RimWorldWin_Data/Mono/data-16247A40.dll
Non platform assembly: data-16275FA0 (this message is harmless)
Fallback handler could not load library C:/Program Files (x86)/Steam/steamapps/common/RimWorld/RimWorldWin_Data/Mono/data-16275FA0.dll
Non platform assembly: data-16279FA8 (this message is harmless)
Fallback handler could not load library C:/Program Files (x86)/Steam/steamapps/common/RimWorld/RimWorldWin_Data/Mono/data-16279FA8.dll
Non platform assembly: data-162D3008 (this message is harmless)
Fallback handler could not load library C:/Program Files (x86)/Steam/steamapps/common/RimWorld/RimWorldWin_Data/Mono/data-162D3008.dll
Non platform assembly: data-162E6008 (this message is harmless)
Fallback handler could not load library C:/Program Files (x86)/Steam/steamapps/common/RimWorld/RimWorldWin_Data/Mono/data-162E6008.dll
Non platform assembly: data-1628FB68 (this message is harmless)
Fallback handler could not load library C:/Program Files (x86)/Steam/steamapps/common/RimWorld/RimWorldWin_Data/Mono/data-1628FB68.dll
Non platform assembly: data-0F4B25F8 (this message is harmless)
Fallback handler could not load library C:/Program Files (x86)/Steam/steamapps/common/RimWorld/RimWorldWin_Data/Mono/data-0F4B25F8.dll
Non platform assembly: data-0F4B5400 (this message is harmless)
Fallback handler could not load library C:/Program Files (x86)/Steam/steamapps/common/RimWorld/RimWorldWin_Data/Mono/data-0F4B5400.dll
Non platform assembly: data-0F4B6808 (this message is harmless)
Fallback handler could not load library C:/Program Files (x86)/Steam/steamapps/common/RimWorld/RimWorldWin_Data/Mono/data-0F4B6808.dll
OnLevelWasLoaded was found on ModInitializerComponent
This message has been deprecated and will be removed in a later version of Unity.
Add a delegate to SceneManager.sceneLoaded instead to get notifications after scene loading has completed
 
(Filename:  Line: 375)

Type ModInitializer probably needs a StaticConstructorOnStartup attribute, because it has a field obj of type GameObject. All assets must be loaded in the main thread.
 
(Filename: C:/buildslave/unity/build/artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 42)

[HugsLib] v2.3.3 initialized WorkTab, BirdsAndBees, HandMeThatBrick, AllowTool, FluffyBreakdowns
 
(Filename: C:/buildslave/unity/build/artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 42)

[HugsLib] Dangerous detour detected! HediffGiver.TryApply to _HediffGiver.TryApply (assembly: Fluffy_BirdsAndBees). Reason: Methods are not call compatible: Parameter count mismatch
 
(Filename: C:/buildslave/unity/build/artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 42)

[HugsLib] Dangerous detour detected! <MakeNewToils>c__Iterator31.<>m__91 to _JobDriver_Lovin.FinishAction (assembly: Fluffy_BirdsAndBees). Reason: Methods are not call compatible: Parameter count mismatch
 
(Filename: C:/buildslave/unity/build/artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 42)

[BirdsAndBees] ready for lovin'
 
(Filename: C:/buildslave/unity/build/artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 42)

**Comment by FluffierThanThou** [comment]
Thanks, nothing jumps out immediately, so I'll investigate further. Save game certainly helps there :)

**Comment by Chaza218** [comment]
https://www.reddit.com/r/RimWorld/comments/5p1l2m/heystop_that/ 

Maybe related? Might be some form of base game bug instead? 

also have a SS of the main offender from my save file (Pyotyr) in the act of reaserching.

**Comment by rsw0x** [comment]
Experiencing the same issue, @Chaza218 could you list the mods you have incase it's a conflict to narrow it down easier?

**Comment by Chaza218** [comment]
https://imgur.com/a/IGXHY

**Comment by Chaza218** [comment]
Not only does it seem to be workers doing disallowed work types, they seem to be doing it with no.1 priority

**Comment by Yithend21** [comment]
Hi,
   I have been using this mod for a while without issues but suddenly starting to experience this issue today within all saves and new games.
 The real problem might be all work types being enable for all colonists after loading a save, mostly likely after mod list has changed.
   In the past, whenever mod list changed, all work type will be enabled for all pawn, and when I open work tab, a message will show on the top left corner and all work priorities will be reset.  But now the reset won't happen any more.

Mods I added recently
Expanded incidents by Psychology
ED-laser drill
Fluffy Research tree
Lamia  (def only mod)
Nekomusume (def only mod)
Allow tool
A world without hat
Colonist Bar KF
Advancing Body and Clothing (def only)
Storage Search and its Allow flesh patch
FashionRIMsta
Quality builder
AC-Enhanced Hauling

**Comment by Yithend21** [comment]
This is my log, a bit too looooong though
[output_log.txt](https://github.com/FluffierThanThou/WorkTab/files/723982/output_log.txt)

and mod config
<ModsConfigData>
  <buildNumber>1393</buildNumber>
  <activeMods>
    <li>Core</li>
    <li>818773962</li>
    <li>839005762</li>
    <li>Override</li>
    <li>735106432</li>
    <li>751841890</li>
    <li>732569232</li>
    <li>733113011</li>
    <li>CombatRealism-1.6.9.5</li>
    <li>High Caliber</li>
    <li>High Caliber (Combat Realism Patch)</li>
    <li>725956940</li>
    <li>CombatRealism EPOE</li>
    <li>MedievalShields-master</li>
    <li>Medieval Times (v. 1.54.A16) - CR patch v0.1</li>
    <li>704181221</li>
    <li>704182588</li>
    <li>821655202</li>
    <li>Misc_Patch_-_Core_-_CombatRealism</li>
    <li>Orassan (Combat Realism Patch)</li>
    <li>Orassan (EPOE Patch)</li>
    <li>726884610</li>
    <li>ED-Shields-CR</li>
    <li>709317151</li>
    <li>733997423</li>
    <li>832333531</li>
    <li>836308268</li>
    <li>834016280</li>
    <li>747313773</li>
    <li>826998327</li>
    <li>775184718</li>
    <li>792561111</li>
    <li>775184481</li>
    <li>784370602</li>
    <li>834823750</li>
    <li>818134054</li>
    <li>822180758</li>
    <li>817996020</li>
    <li>725130005</li>
    <li>832990295</li>
    <li>731111514</li>
    <li>725447220</li>
    <li>776679895</li>
    <li>725949967</li>
    <li>717575199</li>
    <li>761219125</li>
    <li>725623521</li>
    <li>728314182</li>
    <li>784327493</li>
    <li>837080832</li>
    <li>724602224</li>
    <li>708455313</li>
    <li>727309536</li>
    <li>739089840</li>
    <li>705924057</li>
    <li>817231829</li>
    <li>746425621</li>
    <li>753498552</li>
    <li>822470192</li>
    <li>780996548</li>
    <li>715565817</li>
    <li>715565262</li>
    <li>725465444</li>
    <li>830221184</li>
    <li>760708576</li>
    <li>755226916</li>
    <li>758810805</li>
    <li>788610933</li>
    <li>796346900</li>
    <li>Rimfire 2.2 CR-1.6.9.2</li>
    <li>761379469</li>
    <li>728315620</li>
    <li>728318507</li>
    <li>725219116</li>
    <li>740930354</li>
    <li>799834506</li>
    <li>835555932</li>
    <li>AdditionalLighting-AdditionalLighting1.10</li>
    <li>840043916</li>
    <li>817986239</li>
    <li>786233894</li>
    <li>NSF_Drugs</li>
    <li>839704611</li>
    <li>843437166</li>
    <li>843504745</li>
    <li>838336462</li>
    <li>kNumbers-0.6.0</li>
    <li>Additional Joy Objects</li>
    <li>SeedsPlease</li>
    <li>SeedsPlease-VG</li>
    <li>841915667</li>
    <li>812653710</li>
    <li>FluffyBreakdowns</li>
    <li>793978416</li>
    <li>LEDTEC</li>
    <li>ResearchList</li>
    <li>844084979</li>
    <li>844615367</li>
    <li>847634810</li>
    <li>RW_ResearchTree</li>
    <li>722086956</li>
    <li>845431906</li>
    <li>846414777</li>
    <li>761421485</li>
    <li>821065788</li>
    <li>729908976</li>
    <li>[SS]AdvanceBody&amp;Clothing</li>
    <li>726479594</li>
    <li>771073854</li>
    <li>745193823</li>
    <li>754637870</li>
    <li>796303006</li>
    <li>848309750</li>
    <li>755234383</li>
    <li>755224256</li>
    <li>755227567</li>
    <li>755235157</li>
  </activeMods>

**Comment by Chromaskunk** [comment]
I've got the same problem.  I managed to get a save file where one of my pawns is in the act of doing growing when plant cutting is disabled.  I've tried putting the Work Tabs mod at the top of the list (just under hugslib) and the very bottom of the list and the behavior is the same, but if I remove the mod all illegal actions will no longer be done (after I draft/undraft to cancel their current action).

[Output Log](https://dl.dropboxusercontent.com/u/57598535/Misc/output_log.txt)
[Mods Config](https://dl.dropboxusercontent.com/u/57598535/Misc/ModsConfig.xml)
[Save File](https://dl.dropboxusercontent.com/u/57598535/Misc/Cult%20of%20the%20Frost%20Flanks.rws)

The offending pawn is named Shark, and I've checked several times after changing mod order (and restarting) and disabling the mod.  I load the save, turn off all his work priorities, draft/undraft, and with your mod in he continues plant cutting.  Without your mod he just idles.

Also I'm sorry in advance I have like 104 mods.

**Comment by FluffierThanThou** [comment]
Thanks for all the output_logs and save files everyone!

Sadly, I still haven't been able to find the underlying culprit - there's nothing much in the logs (besides some unrelated errors from other mods), and I'm not going to try debugging with 100+ mods loaded.

So, in an effort to fix this, I've added even more checks to both the in and output of priorities. No disallowed priorities can be saved, and if they somehow still are, they will be reset to zero on retrieval. I've also added some extra logging to hopefully find the real culprits of this bug, so if you encountered it before, please do update the mod, play a bit, and then send me the output_log again *even if you don't get the bug anymore*!

**Comment by Chaza218** [comment]
Is that an update that is live on steam now?

**Comment by FluffierThanThou** [comment]
it is indeed.

**Comment by Yithend21** [comment]
Thanks for the updates. It's working well, and I found something interesting.

First, there are something that is actively adding priorities on the run. the log pops up every several second.

Secondly, there are actually few mods all three of us had in common, I disabled some of them didn't fix the problem.

Third, all works that have problems are hunt and below (crating, hauling, plant cut, managing, both mods added work and vanilla work). I had many pawns who can not doctor or warden but those never appears in the log. (I don't have pawn unable to cook, construct or grow just yet)

Do you have any idea what could caused that? 

https://gist.github.com/HugsLibRecordKeeper/a60fe603c7cd627ae71e527c266ad98e

**Comment by FluffierThanThou** [comment]
this may have been addressed with v0.16.2.0 - please give it a shot and see if it works for you.
https://github.com/FluffierThanThou/WorkTab/releases/tag/v0.16.2.0

**Comment by Yithend21** [comment]
Thank you for the update. I have been using this version during the weekend, so far everything worked perfectly.

**Comment by FluffierThanThou** [comment]
good to hear! Thanks for getting back to me :)
