### ISSUE TITLE
UI/MOD Broken

### ISSUE THREAD

**Issue by KurtCocain** [FluffierThanThou/WorkTab#39]
https://i.gyazo.com/84ec99e9cebd118ed2b3d2b9c463e67e.jpg

I am unsure if it's the UI or the mod not working since I never got it to work properly.
When I click to sort differently it actually changes pawn, according to who's first or last.
Is also doesn't show the time line or any ''job box'' whatever option I do or select.
I tried un-ziping with different software and deleted the previous files/folders but it does not make any difference.

https://i.gyazo.com/b0c286635afadcfd27bb5b2bc168117c.png

This is my mod list. Is there any incompatibilities?

**Comment by KurtCocain** [comment]
I tried to save with it and reload, nothing.
And If I load the game I saved with the addon, without the addon, it goes on vanilla tab but with just one pawn still!

**Comment by FluffierThanThou** [comment]
Thanks for reporting! Please provide an output_log so I can figure out what exactly is going on. You can normally find the output log in the following location;
`C:\Program Files\Steam\steamapps\common\RimWorld\RimWorldWin_Data\output_log.txt`

If you changed the steam install location, alter the path accordingly.

**Comment by FluffierThanThou** [comment]
no reply, closing
