### ISSUE TITLE
compatibility issue with rimeffect/rimgate

### ISSUE THREAD

**Issue by RenaudF** [FluffierThanThou/WorkTab#42]
when loaded together with the worktab, makes pawns do jobs which they should not be able to do

**Comment by FluffierThanThou** [comment]
Can you please describe the steps you took to replicate this issue?

**Comment by RenaudF** [comment]
- load `hugslib > alienHumanoids > rimeffect/rimgate > worktabs ( > prepareCarefully for easier testing )`
 - start with a pawn that can't do a job, `hauling disabled` for example.
 - create stockpile zone, unforbid some items
 - pawn with `hauling disabled` will start hauling items to stockpile

**Comment by FluffierThanThou** [comment]
did you restart the game after adding mods, and did you try starting a new game to see if the error went away?

Also, this may have been addressed with v0.16.2.0 - please give it a shot and see if it works for you.
https://github.com/FluffierThanThou/WorkTab/releases/tag/v0.16.2.0

**Comment by RenaudF** [comment]
I can confirm it's fixed with latest version
