### ISSUE TITLE
WorkTab error

### ISSUE THREAD

**Issue by xbluedreamerx** [FluffierThanThou/WorkTab#45]
Having some issues with WorkTab mod I went through the guide it's for sure just the WorkTab mod that's causing an issue I'll attach a photo with error log and modsconfig.

[output_log.txt](https://github.com/FluffierThanThou/WorkTab/files/737896/output_log.txt)
Active mods
<?xml version="1.0" encoding="UTF-8"?>

-<ModsConfigData>

<buildNumber>1393</buildNumber>

-<activeMods>

<li>Core</li>

<li>725219116</li>

</activeMods>

</ModsConfigData>

![wordtabbug](https://cloud.githubusercontent.com/assets/25422882/22408870/98ece590-e64e-11e6-9698-25c9f144ad66.gif)

**Comment by FluffierThanThou** [comment]
Hi there,

You need to install HugsLib, and have it loaded _before_ Work Tab. Loading HugsLib right after Core is generally a good idea.
