### ISSUE TITLE
Bug when loading map (crash to main menu)

### ISSUE THREAD

**Issue by TheBarbarianzim** [FluffierThanThou/WorkTab#47]
I recently have a bug that the game fails to load all savefiles.
I cannot reproduce the bug. It seems that after some time playing loading and saving the game, when I reset my computer and try to load the game again, then I cannot load any of the saves.
I'll send the complete log file and one of the save files.

The log file can be found here: https://gist.github.com/2ce379ffd1a895f2774518c20f874afb
[Prodigios2.zip](https://github.com/FluffierThanThou/WorkTab/files/769814/Prodigios2.zip)

**Comment by TheBarbarianzim** [comment]
That log seems to big.
I'll add the log from the output_log.txt
[output_log.txt](https://github.com/FluffierThanThou/WorkTab/files/769828/output_log.txt)

Here are the important lines in my opinion:
Exception from asynchronous event: System.Exception: current/saved workgiver lists not initialized.
  at Fluffy_Tabs.WorldObject_Priorities.GetSavedWorkgiverIndex (RimWorld.WorkGiverDef workgiver) [0x00000] in <filename unknown>:0 
  at Fluffy_Tabs.PawnPrioritiesTracker.LoadPrioritiesFromString () [0x00000] in <filename unknown>:0 
  at Fluffy_Tabs.PawnPrioritiesTracker.ExposeData () [0x00000] in <filename unknown>:0 
  at Verse.PostLoadInitter.DoAllPostLoadInits () [0x00000] in <filename unknown>:0 
  at Verse.Game.LoadGame () [0x00000] in <filename unknown>:0 
  at Verse.SavedGameLoader.LoadGameFromSaveFile (System.String fileName) [0x00000] in <filename unknown>:0 
  at Verse.Root_Play.<Start>m__736 () [0x00000] in <filename unknown>:0 
  at Verse.LongEventHandler.RunEventFromAnotherThread (System.Action action) [0x00000] in <filename unknown>:0

**Comment by FluffierThanThou** [comment]
thanks for the report. Could you also upload the save file somewhere? (you might want to zip it first)

**Comment by TheBarbarianzim** [comment]
The save file is in the first post: the link "Prodigios2.zip"
Now, looking at it it is confusing that there are two different links on the first post, one for the log file generated by the game and the other with the save file.
If the second link does not work, I can reupload it.
Thanks for the mod by the way.

**Comment by FluffierThanThou** [comment]
ok... your game has somehow not saved the actual priorities object, which is a bit of a problem. I have no idea how that happened, and the log with information about saving it has been overwritten by the log you posted....

Not much I can do at the moment, sorry. I did remove references to WorkTab in your savegame, so at least you should be able to load it again, which is something ;). I'd be much obliged if you could check your console for any errors the next few times you save, and tell me about any errors you might get.

[Prodigios2.zip](https://github.com/FluffierThanThou/WorkTab/files/772407/Prodigios2.zip)

**Comment by TheBarbarianzim** [comment]
Thank you very much.
I'll play more with the game. If I understood correctly, then the game, upon launching, overwrites anything in the output_log.txt.
I'll keep different backups of it in case the bug appears again.

**Comment by TheBarbarianzim** [comment]
Tried a lot to break everything again, but I couldn't.
I guess that this was either fixed in a newer version or I simply got very unlucky with conflicts with other mods.
