### ISSUE TITLE
Error when loading save file

### ISSUE THREAD

**Issue by Adventurer13** [FluffierThanThou/WorkTab#48]
I am encountering an error when trying to load any of my save files as it won't load and presents a debug log on the menu screen. It appears from my inspection that it relates to the work giver priorities, although, you best check as well.
I was able to load this save file last on 12th before all the updates to your mods (yours are the only ones that have updated since then). Today, which is the next time I am loading it, I have had no luck.

I have attached links to my save file and output_log below.

[Save.zip](https://github.com/Adventurer13/Saves/blob/master/Save.zip)
[output_log.txt](https://github.com/Adventurer13/Saves/blob/master/output_log.txt)

I trust that you'll understand it more.

Thanks you,
Adventurer13

**Comment by FluffierThanThou** [comment]
found and fixed the issue, just testing it a bit before I release the fix.

**Comment by FluffierThanThou** [comment]
aight, it's a simple issue that only applies to loading save games created with 0.16.1.x of the mod. I've tested all the load/save scenarios I could think of and had saves lying around for, and it seems to work.

I can't actually test with your specific save game (don't have the mods, don't have the time to get them), so please let me know what happens.

**Comment by Adventurer13** [comment]
It is working now. Thanks for the update! I thought the amount of mods I have might be an issue with the save and hoped the output_log would suffice.
