### ISSUE TITLE
After Save/Load, Colonist Work Assignments Are Reset / Seemingly Random

### ISSUE THREAD

**Issue by maarxx** [FluffierThanThou/WorkTab#49]
I am having a problem, I am noticing that upon Loading a game, the work priorities are "reset", and do not at all match what they were when the game was Saved.

By "reset" I mean that the settings are just seemingly random, completely different, without any correlation to what they were set to previously.

It is as if the game somehow failed to load all of the work assignments and just defaulted back to what it would have given those colonists on a brand new world start, or after each colonist first being recruited, when the game first takes its own best guess at setting work.

Below is a Google Drive folder containing my ModsConfig.xml and output_log.txt and a .RAR compression of the entire directory ...

%appdata%/../LocalLow/Ludeon Studios/RimWorld by Ludeon Studios

... including /Saves/ subdirectory.

https://drive.google.com/drive/folders/0BwvimyCo5Ar4M08zUWd6RWF1eU0?usp=sharing

**Comment by maarxx** [comment]
It does not happen consistently every time, I can play a session and save and load several times and everything is maintained, sometimes I can even quit the game and come back in and everything is maintained, and then the next time after that, when I quit and return, work assignments are reset.

**Comment by FluffierThanThou** [comment]
Thanks for reporting. I've been busy with work more than usual the last couple of weeks, and will be unable to do much for a couple more weeks. I'll try and get it fixed asap afterwards.

**Comment by maarxx** [comment]
I've noticed a couple more things:

1. It doesn't strictly have to be Save-QuitOS-StartGame-Load. On a couple of occasions, I have just Saved the game and then immediately Loaded the save to find the priorities all reset.

2. As weird as it sounds, it seems to happen much more frequently in the early stages of a colony. In the first 30-60 days, it seems to happen a lot, yet in older colonies with a couple years, it doesn't happen nearly as much.

**Comment by maarxx** [comment]
I cleaned up my comments and genericized this ticket, to make it more relatable to others, to reduce duplication.

**Comment by maarxx** [comment]
Issue alluded to in comments on Steam Workshop page (times US Eastern):

minute_of_decade Mar 17 @ 4:31am 
Hi I keep having a weird bug. Your mod was working pretty well until lately. I launch a new colony everything seems fine, but after a few loads, the work priority become totally mess up. Removing the priorities I put before and givin new ones (and generally not to the best pawns). I haven't the slighlest idea of what it causing it.

Graymann Mar 20 @ 2:15am 
Have the same issue as minute_of_decade, is there a known cause to this?

Fluffy  [author] Mar 20 @ 5:25am 
@Graymann, minute_of_decade; there's some leftover code that was dealing with bugs in earlier versions, which is now itself starting to cause problems.  I need to revise and simplify my code, but I'll likely wrap that up together with the upcoming A17 update.

NexionSE of the Cm.G. Mar 21 @ 8:19pm 
i have the same problem as minute_of_decade after every load work prios gets shifted and some stops working and go idle even if work prios set on it still

Issue alluded to in RimWorld Discord #rimworld (times US Eastern):

sma342 - Today at 10:27 AM
something is breaking worktab for me

sma342 - Today at 10:28 AM
everytime i reload save it scrambles my work tab

DianaWinters - Today at 10:29 AM
That bug is why I stopped using it

**Comment by ridjack** [comment]
I'm also experiencing this; in my current game, it's only happening to recruits who joined after my original five tribals. 
![rimworldworktabbugreport](https://cloud.githubusercontent.com/assets/22875626/26471417/8df36d68-416f-11e7-90d8-5fa305aa44db.png)

Only consistent thing I've noticed so far.

**Comment by FluffierThanThou** [comment]
I've completely rewritten the priority code for the A17 (pre-release) version, it should be much more robust now.

**Comment by HoloShaii** [comment]
Problem seems to be back on my end, after loading a recently saved game, it reset the work priorities of my starting pawns in a seemingly random fashion.

**Comment by EpyonComet** [comment]
Confirming the above issue. I haven't tested thoroughly, but in my case, it looks like starting colonists' priorities get scrambled, while the others stay intact.

**Comment by FSchacht** [comment]
> Confirming the above issue. I haven't tested thoroughly, but in my case, it looks like starting colonists' priorities get scrambled, while the others stay intact.

I can confirm that as well. Also that it only effects starting colonists.

**Comment by mrkorb** [comment]
Happening to me as well, but it only seems to happen after the first time I save and exit.  Upon reloading the save, all priorities are reset to their default of 3. It appears to correctly save after that.
