### ISSUE TITLE
After colonists died, unable to save

### ISSUE THREAD

**Issue by JonBoyleCoding** [FluffierThanThou/WorkTab#50]
I'm not sure exactly which of your mods this might be an issue with (or if it's compatability with another mod), but after a raid, I ended up with many colonists dying. After which, the following error appeared when trying to save. I've ended up posting here, because when reading the log I saw references to 'fluffy' and 'pawnprioritiestracker'.

![rimworld_error1](https://cloud.githubusercontent.com/assets/630329/23336141/bc01f496-fbbe-11e6-8714-4f7bc3deaf50.png)
![rimworld_error2](https://cloud.githubusercontent.com/assets/630329/23336143/bf69ac00-fbbe-11e6-8a60-86fecc948a94.png)
![rimworld_error3](https://cloud.githubusercontent.com/assets/630329/23336144/c1dd78d6-fbbe-11e6-8501-1db267bc6e65.png)

**Comment by colinfike** [comment]
I have the same issue.

**Comment by FluffierThanThou** [comment]
Thanks, I think I know what's going on, will try and fix soon(ish)

**Comment by FluffierThanThou** [comment]
I've completely rewritten the priority code for the A17 (pre-release) version, it should be much more robust now.
