### ISSUE TITLE
Should Offer Function to Increment Column Only Where Existing Assignment

### ISSUE THREAD

**Issue by maarxx** [FluffierThanThou/WorkTab#57]
So I can Shift+Click on a column to increment/decrement the numeric priority for everybody, but if incrementing, it also assigns the task (starting at lowest priority) to every pawn who didn't already have it.

It would be cool if I could increment the priority only for pawns already having a numeric priority assigned.

**Comment by FluffierThanThou** [comment]
interesting idea, I think I can implement that quite easily with an extra modifier, e.g. Ctrl+Shift+click/scroll

**Comment by benbaginski** [comment]
How about making it a mod setting? Shift-Click only affects assigned.

Actually if I had my way, shift click would never unassign or assign pawns to a job. Instead it would max or min out at 9 or 1, only affecting those assigned to the job.

**Comment by MyrddinE** [comment]
I agree with @benbaginski that the current behavior has very little utility (none?), and the change suggested would be better in almost every case. When I'm decrementing a single pawn wrapping is fine... but when I'm decrementing four pawns (with possibly different priorities) at once, using a ceiling and floor, and not touching blank priorities, has more real world use-cases (situations where that behavior will make the change you desire and save you time over changing each pawn individually).
