### ISSUE TITLE
Saved games corrupted: "System.Exception: current/saved workgiver lists not initialized."

### ISSUE THREAD

**Issue by Eunomiac** [FluffierThanThou/WorkTab#58]
I am consistently unable to load saved games that have been played for more than an hour or so.  The output_log says, in relevant part:

>`Exception from asynchronous event: System.Exception: current/saved workgiver lists not initialized.
>   at Fluffy_Tabs.WorldObject_Priorities.GetSavedWorkgiverIndex (RimWorld.WorkGiverDef workgiver) [0x00000] in <filename unknown>:0 
>   at Fluffy_Tabs.PawnPrioritiesTracker.LoadPrioritiesFromString () [0x00000] in <filename unknown>:0 
>   at Fluffy_Tabs.PawnPrioritiesTracker.ExposeData () [0x00000] in <filename unknown>:0 
>   at Verse.PostLoadInitter.DoAllPostLoadInits () [0x00000] in <filename unknown>:0 
>   at Verse.Game.LoadGame () [0x00000] in <filename unknown>:0 
>   at Verse.SavedGameLoader.LoadGameFromSaveFile (System.String fileName) [0x00000] in <filename unknown>:0 
>   at Verse.Root_Play.<Start>m__736 () [0x00000] in <filename unknown>:0 
>   at Verse.LongEventHandler.RunEventFromAnotherThread (System.Action action) [0x00000] in <filename unknown>:0 `

I've tried to reproduce this problem by:

1. Starting a new game
1. Fiddling around with the WorkTab settings
1. Saving, and then trying to reload the game

However, I can't seem to pin down the exact issue that causes the crash.  I do make use of all the great features in your mod, from scheduling different priorities at different times, to saving favourites (are those the "workgiver lists?"), to fine-tuning priorities using the expanded work tab, so I'm afraid it could be just about anything.

I've included my output_log.txt and my ModsConfig.xml file below:

[output_log.txt](https://github.com/FluffierThanThou/WorkTab/files/967412/output_log.txt)
[ModsConfig.xml.txt](https://github.com/FluffierThanThou/WorkTab/files/967413/ModsConfig.xml.txt)

Thanks for your great work on this mod! Hopefully I've provided enough information for you to pin down the problem, because I absolutely love this mod and playing RimWorld without it just isn't the same!

Please let me know if you need any further information from me, such as saved games (including one from a game that loads fine, and then another save from that same game an hour or so later that crashes with the above error), but I'm not sure how helpful they'll be without all of my mods!

**Comment by Eunomiac** [comment]
The fix you supplied in [Issue 29](https://github.com/FluffierThanThou/WorkTab/issues/29) was able to fix my game:

> A mod added a workgiver/worktype, which throws off WorkTab. This is a known bug which I'll fix shortly (hopefully).
>
>For now, you can fix it by temporarily disabling workTab.
>
>- Remove WorkTab, reload RW.
>- Open the savegame, save it again.
>- Re-enable WorkTab, restart RW.
>- Open the save again, work settings will be reset to 'simple' mode, but it should work again.

... but that, unfortunately, erases all of my carefully-tuned settings.  

Could this problem, as in Issue 29, be related to another mod adding a new workgiver/worktype?  I have several mods that do that, as well as the [Refactored Work Priorities](https://steamcommunity.com/sharedfiles/filedetails/?id=774989162) mod, which I thought might be a culprit.

**Comment by Eunomiac** [comment]
I'm pretty sure the problem has to do with saving favourite work configurations:  I played for several hours without using that feature (but using everything else) and was able to load the save game just fine.  

Both other times I was able to play for only an hour or so before my save was corrupted, and on both of those occasions I was creating and deleting favourite work configurations regularly.

**Comment by FluffierThanThou** [comment]
I've completely rewritten the priority code for the A17 (pre-release) version, it should be much more robust now.
