### ISSUE TITLE
Changing priorities by scrolling only works for the first 3 colonists

### ISSUE THREAD

**Issue by Mythos** [FluffierThanThou/WorkTab#60]
Hey there,

I've noticed a bug for some time now:
When I generally prefer scrolling over clicking when changing the manual work priorities. I've noticed that the last entry (i.e. last colonist) does not allow scrolling.

Now I've also noticed, that only the first 3 colonists allow changing priorities by scrolling. (maybe above text is irrelevant, because I've started with 4 colonists => last one is >3)
When SHIFT + Scroll on the work type (like firefighting) it works for all colonists.

Regards,
Stefan

**Comment by FluffierThanThou** [comment]
interesting, I'll have a look!

**Comment by Mythos** [comment]
Hmm I just read on Steam, that the mod "Quarry" could cause this problem as it adds a new worktype.
http://steamcommunity.com/sharedfiles/filedetails/?id=936490638

**Comment by FluffierThanThou** [comment]
Nah I'm fairly sure this is something else entirely 

(I'm 99% certain it's related to how RimWorld does scrollviews; they 'consume' scroll events before the content is rendered so the content doesn't get the event anymore. What I'm yet to figure out is why in heaven it does work for the first three rows... )

**Comment by Mythos** [comment]
So you are able to reproduce the problem?

**Comment by FluffierThanThou** [comment]
Yeah, consistently. There's something really fishy going on in a bit of code that Tynan uses as a wrapper around Unity's scrollView. If I just use Unity, all is well - but if I use Tynan's wrapper, it bugs out in various ways.

I've added a patch that basically makes Tynans' wrapper just call Unity code directly, so it works now. I'm a bit afraid something else will break, as I have no idea what purpose all the extra code in Tynan's wrapper was meant to serve... I've asked someone with access to the source code to have a look and see if he can give me an idea of why it works the way it does.

**Comment by Mythos** [comment]
Thanks for your response. Good to hear, that it's not directly a bug of WorkTab! ;-)
