### ISSUE TITLE
Conflicts with "EdB Prepare Carefully"

### ISSUE THREAD

**Issue by PaszaVonPomiot** [FluffierThanThou/WorkTab#66]
Conflicts with "EdB Prepare Carefully"
https://gist.github.com/HugsLibRecordKeeper/cdf81af9c581dad804abdd6647633b1e#file-output_log-txt-L1662

Steps to reproduce:
1. Enable debugging
2. New colony > next > next > next > Select random site > next > Prepare carefully > Start > Confirm
(so basically you go with all default settings even in Prepare Carefully window)
3. Once pods have landed and people are moving save the game
4. Check debug log for warnings 

Also there's error in debug log after loading that save but you can still play. The error says:
`Null key while loading dictionary of Verse.Pawn and WorkTab.PawnPriorityTracker.`

**Comment by FluffierThanThou** [comment]
hmm, yeah, I've had issues with that in the past actually. It seems like PC keeps 'ghost pawns' around, which the game somehow tries to save (which partially succeeds) and then load (which fails). 

Like you said, it's not a breaking bug - so not a high priority for me right now. I'll look into it soonish.
