### ISSUE TITLE
Horizontal Clutter

### ISSUE THREAD

**Issue by RenaudF** [FluffierThanThou/WorkTab#67]
Depending on how many mods add new job types, the advanced work tab can get so congested that it is useless as it is impossible to see what values are in the grid, never mind updating them.

Here are a list of ideas that could help mitigate:
 - horizontal scroll bar
 - collapsible groups
 - columns grouping

**Comment by RenaudF** [comment]
I wasn't aware of the column filter feature, this could be made more transparent, perhaps using in game alert message?

**Comment by FluffierThanThou** [comment]
Making users more aware of the various functions of the mod is probably a good idea, I keep getting surprised by the number of people that do not read tooltips. I've added a separate issue here; #70.

That said, we do need some way of reducing clutter - probably a scrollbar. I'll also look into bringing horizontal labels back to make them a bit more readable.

**Comment by MrClon** [comment]
Optional horizontal scroll or/and vertical labels (as in that video) would be great. 
It's hard to find tooltrips when window content so unreadable

**Comment by FluffierThanThou** [comment]
vertical labels are back, I'll look at a scroll bar next - but that might get a bit tricky

**Comment by FluffierThanThou** [comment]
I've added a horizontal scroll bar. There's a couple of issues with it that I'd like to fix in the long(er) term;

 - The scrollbar applies to _all_ 'table' type tabs that exceed their maximum width (detours `PawnTable.RecacheIfDirty` and `PawnTable.PawnTable_OnGUI`). I'm thinking of making this a stand-alone mini-mod if it introduces UI issues in other mods.
 - The scrollable area includes the row 'headers'; pawn labels are scrolled off-screen. I'd like to be able to 'freeze' certain columns, but that's for another day.

**Comment by bustedbunny** [comment]
![image](https://user-images.githubusercontent.com/30902981/47927454-cb502a00-dedc-11e8-96af-9ea483360bd6.png)
Currently unreadable with mods. I guess scrolling will solve it.
