### ISSUE TITLE
Job types not displayed vertically

### ISSUE THREAD

**Issue by Schlecki** [FluffierThanThou/WorkTab#68]
This is what the expanded tab looks like for me, no matter what I do. I deactivated all mods, started a new game, but the text is displayed horizontally and cluttered, as are the checkboxes (see screenshot).

![rimworld](https://user-images.githubusercontent.com/1459597/29584367-cdd5590a-8783-11e7-9115-d0c994442e96.png)
[output_log.txt](https://github.com/FluffierThanThou/WorkTab/files/1243188/output_log.txt)
[ModsConfig.xml.txt](https://github.com/FluffierThanThou/WorkTab/files/1243189/ModsConfig.xml.txt)

**Comment by FluffierThanThou** [comment]
Yeah, thats normal. The video on the steam page is from the A16 and earlier versions, A17 required a complete redesign.

I'll look into bringing this back as part of #67
