### ISSUE TITLE
Conflict with Achtung?

### ISSUE THREAD

**Issue by FluffierThanThou** [FluffierThanThou/WorkTab#71]
> I've fiund a conflct with (I believe) Acthung!. When I use it to prioritise jobs, and then click on the work Tab, the tab shows only the colonists up to the one selected for the Achtung! priotised work, such as sowing or cleaning a room.
> But maybe you know about that one already... :-)

I'm willing to bet that achtung is dynamically generating the jobdefs for room jobs. Need to investigate, achtung is brilliant, and I don't want to be incompatible with it.

**Comment by MoneyAllDay** [comment]
I also have Acthung, same here, last time i selected all pawns to sow some rooms(enclosed by walls) all of them disappeared from the work tab.
