### ISSUE TITLE
Can't see the tabs

### ISSUE THREAD

**Issue by Andrew226** [FluffierThanThou/WorkTab#83]
![20180117210632_1](https://user-images.githubusercontent.com/35472995/35077381-15296100-fbcb-11e7-98a8-0b1201d51b45.jpg)

It doesn't display the tabs correctly when it is in extended view.

**Comment by Andrew226** [comment]
Makes it really hard to individually sort them. So for right now I won't use this view, but I would like it if you could assist with this issue whenever you can.

**Comment by FluffierThanThou** [comment]
duplicate of #67
