### ISSUE TITLE
Missing icons on game start? is:bug

### ISSUE THREAD

**Issue by AmauryLepicard** [FluffierThanThou/WorkTab#85]
Hi Fluffy,
When enabling the mod in the modlist, I get a bunch of errors messages telling me there are missing icons. As a result, WorkTab and other mods are disabled.

Here is my error log:
https://gist.github.com/HugsLibRecordKeeper/9e84eb5f2fd784cda7e1d50e9fc2f27f

 The errors appears from line 1 to 224 .
Thanks!

**Comment by FluffierThanThou** [comment]
I've been unable to replicate this.
