### ISSUE TITLE
Keep relative priority when modifying collapsed priorities

### ISSUE THREAD

**Issue by jacobEAdamson** [FluffierThanThou/WorkTab#91]
Right now, you can expand a column and increase the priority of one the tasks inside. Once the column is collapsed again though, modifying the priority of the collapsed task overwrites your more granular priorities. It would be nice if the increasing or decreasing the priority of the group remembered the offset of task priorities. Example: Hauling as a group is prio 3, I expand the group and set refilling refuelable to 2. I collapse the group, and increase hauling priority. I'd like refuelable prio to go to 1, and all other prios in hauling to go to 2

**Comment by zuaresoft** [comment]
Fluffy this is a good note about worktab because sometimes you need set refuel to max priority for example, but if you set the refuel as 1, another jobs group with prioritys smaller (2,3,4) but that stay before in the main list it will not run if not after refuel..
