### ISSUE TITLE
Hide Pawns - colours - groups - save &load configuration

### ISSUE THREAD

**Issue by zuaresoft** [FluffierThanThou/WorkTab#93]
* An option for hide Pawns in worktab, when we have 20 pawns is confuse but if you hide 17 pawns you can select the 3 hunters and work on them.

* Colours for pawns in list, when we open the worktab, we see 20 messy pawns but we can mark the 3 hunters with blue, 2 cheff with red, you know.. only more order

* An option for save actual pawn configuration, and in the future put it in the pawns selected.

* Set work groups, this widget (or no widget) is for hunter group, and next we tap the widget, look the widget show the hunter list. this draggable widget and the worktab UI are the same but only show the hunters in it, the chefs in it, you know.

**Comment by FluffierThanThou** [comment]
Interesting ideas, but somewhat out of scope for the current mod.
